name: Danny DB
favicon: null
layout_spectrum: 0.03919448843225837
typography_spectrum: 0.24891791981644928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.46443302067928016
  lightness: 0.6310103130526841
  saturation: 0.33227262110449374
  rhythmicContrast: 0.5653306236490607
purpose: []
